### ISSUE TITLE
after enable, give me an error.

### ISSUE THREAD

**Issue by BaxAndrei** [sirhypernova/namelessmc-filemanager#5]
https://i28.servimg.com/u/f28/17/31/96/85/screen21.png
https://i28.servimg.com/u/f28/17/31/96/85/screen22.png

**Comment by sirhypernova** [comment]
What is your language setting?

**Comment by sirhypernova** [comment]
I believe the issue is that the language constant isn't exactly `Romanian`

**Comment by BaxAndrei** [comment]
I I have tried both with the Romanian who is in the module, as well as with the EnglishUK

**Comment by sirhypernova** [comment]
Hmm that's odd

**Comment by sirhypernova** [comment]
To confirm, you are using NamelessMC v2-pre3?

**Comment by BaxAndrei** [comment]
Pre4

**Comment by sirhypernova** [comment]
That might be why, I made it for pre-3

**Comment by sirhypernova** [comment]
Soon if I get the chance, I can update it to pre-4

**Comment by BaxAndrei** [comment]
Ok, thanx, I will wait.

**Comment by StormyIceLeopard** [comment]
When will this get updated for pre-release 7?
What about pre-release 8?

**Comment by sirhypernova** [comment]
I should've mentioned a bit ago. I don't plan on updating this anymore. I'm going to archive the repo.
